import rsa

banner = \
'''; -----------------------------------------
; | This file is auto-generated by script |
; |             Do NOT edit it            |
; -----------------------------------------'''

with open('rsaKey.inc', 'w') as f:
	# Add description
	d, n = rsa.genKey()
	f.write(banner + '\n')
	f.write('KERNEL_KEY_D equ {}'.format(rsa.d))
	f.write('\n')
	f.write('KERNEL_KEY_N equ {}'.format(rsa.n))